# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PortScanner(object):
    def setupUi(self, PortScanner):
        PortScanner.setObjectName("PortScanner")
        PortScanner.resize(606, 575)
        PortScanner.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 170, 255, 255), stop:1 rgba(170, 170, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(PortScanner)
        self.centralwidget.setObjectName("centralwidget")
        self.hostBox = QtWidgets.QTextEdit(self.centralwidget)
        self.hostBox.setGeometry(QtCore.QRect(230, 30, 121, 31))
        self.hostBox.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.hostBox.setObjectName("hostBox")
        self.startBox = QtWidgets.QTextEdit(self.centralwidget)
        self.startBox.setGeometry(QtCore.QRect(230, 80, 121, 31))
        self.startBox.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.startBox.setObjectName("startBox")
        self.endBox = QtWidgets.QTextEdit(self.centralwidget)
        self.endBox.setGeometry(QtCore.QRect(230, 130, 121, 31))
        self.endBox.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.endBox.setObjectName("endBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 90, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 291, 531, 221))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.listWidget.setObjectName("listWidget")
        self.scanButton = QtWidgets.QPushButton(self.centralwidget)
        self.scanButton.setGeometry(QtCore.QRect(130, 200, 75, 23))
        self.scanButton.setObjectName("scanButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.stopButton.setObjectName("stopButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(370, 200, 75, 23))
        self.resetButton.setObjectName("resetButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 47, 13))
        self.label_4.setStyleSheet("background-color: rgb(170, 255, 255)")
        self.label_4.setObjectName("label_4")
        PortScanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PortScanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 21))
        self.menubar.setObjectName("menubar")
        PortScanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PortScanner)
        self.statusbar.setObjectName("statusbar")
        PortScanner.setStatusBar(self.statusbar)

        self.retranslateUi(PortScanner)
        QtCore.QMetaObject.connectSlotsByName(PortScanner)

    def retranslateUi(self, PortScanner):
        _translate = QtCore.QCoreApplication.translate
        PortScanner.setWindowTitle(_translate("PortScanner", "MainWindow"))
        self.label.setText(_translate("PortScanner", "Host:"))
        self.label_2.setText(_translate("PortScanner", "Start Port:"))
        self.label_3.setText(_translate("PortScanner", "End Port:"))
        self.scanButton.setText(_translate("PortScanner", "Scan"))
        self.stopButton.setText(_translate("PortScanner", "Stop"))
        self.resetButton.setText(_translate("PortScanner", "Reset"))
        self.label_4.setText(_translate("PortScanner", "Results:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PortScanner = QtWidgets.QMainWindow()
    ui = Ui_PortScanner()
    ui.setupUi(PortScanner)
    PortScanner.show()
    sys.exit(app.exec_())
